
name: Auto-comment on labeled issues
on:
  issues:
    types: [labeled]
jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Comment on bug
        if: github.event.label.name == 'bug'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you. We will fix it.'
            })
      - name: Comment on feature
        if: github.event.label.name == 'feature'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thank you, we will consider to include this feature.'
            })
      - name: Comment on discussion
        if: github.event.label.name == 'discussion'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Thanks for starting this discussion! We welcome community input.'
            })
