
name: Auto Comment on New Issue

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  add-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Add comment for bug
        if: github.event.label.name == 'bug'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Thank you. We will fix it.

      - name: Add comment for feature
        if: github.event.label.name == 'feature'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Thank you, we will consider to include this feature.

      - name: Add comment for discussion
        if: github.event.label.name == 'discussion'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.issue.number }}
          body: Thanks for starting this discussion! We welcome community input.
